export const topics = {
	// math topics
	sequence: "الگو و دنباله",
	algebraic_expression: "عبارت های جبری و اتحاد",
	square_root: "رادیکال و توان گویا",
	inequality: "تعیین علامت و نامعادله",
	quadratic_equation: "عبارات درجه دوم",
	equation: "معادلات گویا و گنگ",
	analytic_geometry: "هندسه مختصاتی",
	absolute_value: "قدر مطلق",
	floor_function: "جز صحیح",
	logarithm: "توابع نمایی و لگاریتمی",
	function: "تابع",
	division: "تقسیم چند جمله ای",
	trigonometry: "مثلثات",
	limit: "حد و پیوستگی",
	infinity: "حد نامتنهایی، حد بینهایت، مجانب",
	derivative: "مشتق",
	derivative_application: "کاربرد مشتق",
	// geometry topics
	g10_1: "فصل 1 دهم، ترسیم هندسی و استدلال",
	g10_2: "فصل 2 دهم، تالس و تشابه",
	g10_3: "فصل 3 دهم، چندضلعی ها",
	g10_4: "فصل 4 دهم، تجسم فضایی",
	g11_1: "فصل 1 یازدهم، دایره",
	g11_2: "فصل 2 یازدهم، تبدیل های هندسی",
	g11_3: "فصل 3 یازدهم، روابط طولی مثلث",
	g12_1: "فصل 1 دوازدهم، ماتریس",
	g12_2: "فصل 2 دوازدهم، مقاطع مخروطی",
	g12_3: "فصل 3 دوازدهم، بردار",
	// discrete math topics
	mathematical_reasoning: "استدلال ریاضی",
	divisibility: "بخش پذیری و اعداد اول",
	lcm_gcd: "ب.م.م و ک.م.م",
	division_theorem: "قضیه تقسیم",
	modular_arithmetic: "هم نهشتی و معادله سیاله",
	calendar: "تقویم نگاری",
	graph_theory: "مفاهیم گراف",
	graph_types: "انواع گراف",
	connectivity_path_cycle: "مسیر، دور و همبندی",
	dominating_set: "احاطه گری",
	combinatorics: "شمارش",
	latin_square: "مربع لاتین",
	inclusion_exclusion_principle: "اصل شمول و عدم شمول",
	pigeonhole_principle: "اصل لانه کبوتری",
	// statistics and probability topics
	mathematical_logic: "منطق ریاضی",
	set: "مجموعه و ضرب دکارتی",
	probability: "احتمال",
	descriptive_statistics: "آمار توصیفی",
	inferential_statistics: "آمار استنباطی",
	// physics topics
	p10_1: "اندازه گیری، چگالی",
	p10_2: "ویژگی های فیزیکی مواد، فشار",
	p10_3: "کار، انرژی، توان",
	p10_4: "دما و گرما",
	p10_5: "ترمودینامیک",
	p11_1: "الکتریسیته ساکن",
	p11_2: "جریان الکتریکی و مدار",
	p11_3: "مغناطیس",
	p11_4: "القای الکترومغناطیسی",
	p12_1: "حرکت بر خط راست",
	p12_2: "دینامیک و حرکت دایره ای",
	p12_3: "نوسان و موج",
	p12_4: "برهم کنش های موج",
	p12_5: "فیزیک اتمی",
	p12_6: "فیزیک هسته ای",
	// chemistry topics
	c10_1: "حفظیات درس 1 دهم",
	c10_2: "حفظیات درس 2 دهم",
	c10_3: "حفظیات درس 3 دهم",
	c11_1: "حفظیات درس 1 یازدهم",
	c11_2: "حفظیات درس 2 یازدهم",
	c11_3: "حفظیات درس 3 یازدهم",
	c12_1: "حفظیات درس 1 دوازدهم",
	c12_2: "حفظیات درس 2 دوازدهم",
	c12_3: "حفظیات درس 3 دوازدهم",
	c12_4: "حفظیات درس 4 دوازدهم",
	mixed: "سوال ترکیبی",
	periodic_table: "جدول تناوبی، لایه و زیرلایه",
	electromagnetic_radiation: "نور و پرتو الکترومغناطیسی",
	Lewis_structure: "ساختار لوویس",
	chemical_equation: "موازنه واکنش",
	gas_laws: "رفتار گازها",
	stoichiometry: "استوکیومتری",
	dissolution: "انحلال",
	chemical_bounds: "پیوند ها",
	hydrocarbon: "هیدروکربن ها",
	heat: "دما، گرما و تعادل گرمایی",
	enthalpy: "آنتالپی، آنتالپی سوختن و ارزش سوختی",
	bond_enthalpy: "آنتالپی پیوند",
	hess_law: "قانون هس",
	functional_group: "گروه عاملی",
	chemical_kinetics: "سینتیک",
	polymer: "پلیمر",
	soap: "پاک کننده ها",
	acid_base: "اسید و باز",
	oxidation_state: "عدد اکسایش",
	electrochemical_cell: "سلول های الکتروشیمیایی",
	compounds: "کووالانسی، مولکولی، یونی و فلز",
	activation_energy: "انرژی فعال سازی",
	chemical_equilibrium: "تعادل شیمیایی",
}
